"""Process an existing DCA1000 adc_data.bin file."""

from __future__ import annotations

import argparse
from pathlib import Path

from .adc_reader import AdcCaptureShape, range_doppler_map, read_adc_data


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Read DCA1000 adc_data.bin and export a Range-Doppler map")
    parser.add_argument("--input", required=True, help="Path to adc_data.bin generated by TI DCA1000 CLI")
    parser.add_argument("--frames", type=int, required=True)
    parser.add_argument("--chirps", type=int, required=True)
    parser.add_argument("--rx", type=int, required=True)
    parser.add_argument("--samples", type=int, required=True)
    parser.add_argument("--frame-index", type=int, default=0)
    parser.add_argument("--iq-order", choices=("ti", "iq"), default="ti")
    parser.add_argument("--allow-truncate", action="store_true")
    parser.add_argument("--output", default="captures/range_doppler.png")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    shape = AdcCaptureShape(
        frames=args.frames,
        chirps=args.chirps,
        rx=args.rx,
        samples=args.samples,
    )
    adc = read_adc_data(
        args.input,
        shape,
        iq_order=args.iq_order,
        allow_truncate=args.allow_truncate,
    )

    if args.frame_index < 0 or args.frame_index >= adc.shape[0]:
        raise ValueError(f"--frame-index must be between 0 and {adc.shape[0] - 1}")

    rd = range_doppler_map(adc[args.frame_index])

    import matplotlib.pyplot as plt

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(10, 6))
    plt.imshow(rd, aspect="auto", origin="lower", cmap="jet")
    plt.colorbar(label="Magnitude dB")
    plt.xlabel("Range bin")
    plt.ylabel("Doppler bin")
    plt.title(f"Range-Doppler Map - frame {args.frame_index}")
    plt.tight_layout()
    plt.savefig(out, dpi=150)
    print(f"saved={out} adc_shape={adc.shape}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
